In [1]:
import pandas as pd

In [2]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow'

url = f'{prefix}/yellow_tripdata_2020-01.csv.gz'
url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2020-01.csv.gz'

In [3]:
df = pd.read_csv(url)

/tmp/ipykernel_26794/4176769558.py:1: DtypeWarning: Columns (0: store_and_fwd_flag) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

In [4]:
df.head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2020-01-01 00:28:15,2020-01-01 00:33:03,1.0,1.20,1.0,N,238,239,1.0,6.00,3.0,0.5,1.47,0.0,0.3,11.27,2.5
1,1.0,2020-01-01 00:35:39,2020-01-01 00:43:04,1.0,1.20,1.0,N,239,238,1.0,7.00,3.0,0.5,1.50,0.0,0.3,12.30,2.5
2,1.0,2020-01-01 00:47:41,2020-01-01 00:53:52,1.0,0.60,1.0,N,238,238,1.0,6.00,3.0,0.5,1.00,0.0,0.3,10.80,2.5
3,1.0,2020-01-01 00:55:23,2020-01-01 01:00:14,1.0,0.80,1.0,N,238,151,1.0,5.50,0.5,0.5,1.36,0.0,0.3,8.16,0.0
4,2.0,2020-01-01 00:01:58,2020-01-01 00:04:16,1.0,0.00,1.0,N,193,193,2.0,3.50,0.5,0.5,0.00,0.0,0.3,4.80,0.0
5,2.0,2020-01-01 00:09:44,2020-01-01 00:10:37,1.0,0.03,1.0,N,7,193,2.0,2.50,0.5,0.5,0.00,0.0,0.3,3.80,0.0
6,2.0,2020-01-01 00:39:25,2020-01-01 00:39:29,1.0,0.00,1.0,N,193,193,1.0,2.50,0.5,0.5,0.01,0.0,0.3,3.81,0.0
7,2.0,2019-12-18 15:27:49,2019-12-18 15:28:59,1.0,0.00,5.0,N,193,193,1.0,0.01,0.0,0.0,0.00,0.0,0.3,2.81,2.5
8,2.0,2019-12-18 15:30:35,2019-12-18 15:31:35,4.0,0.00,1.0,N,193,193,1.0,2.50,0.5,0.5,0.00,0.0,0.3,6.30,2.5
9,1.0,2020-01-01 00:29:01,2020-01-01 00:40:28,2.0,0.70,1.0,N,246,48,1.0,8.00,3.0,0.5,2.35,0.0,0.3,14.15,2.5

In [5]:
len(df)

6405008

In [6]:
df['VendorID']

0          1.0
1          1.0
2          1.0
3          1.0
4          2.0
          ...
6405003    NaN
6405004    NaN
6405005    NaN
6405006    NaN
6405007    NaN
Name: VendorID, Length: 6405008, dtype: float64

In [7]:
df['tpep_pickup_datetime']

0          2020-01-01 00:28:15
1          2020-01-01 00:35:39
2          2020-01-01 00:47:41
3          2020-01-01 00:55:23
4          2020-01-01 00:01:58
                  ...
6405003    2020-01-31 22:51:00
6405004    2020-01-31 22:10:00
6405005    2020-01-31 22:50:07
6405006    2020-01-31 22:25:53
6405007    2020-01-31 22:44:00
Name: tpep_pickup_datetime, Length: 6405008, dtype: str

In [8]:
df['tpep_dropoff_datetime']

0          2020-01-01 00:33:03
1          2020-01-01 00:43:04
2          2020-01-01 00:53:52
3          2020-01-01 01:00:14
4          2020-01-01 00:04:16
                  ...
6405003    2020-01-31 23:22:00
6405004    2020-01-31 23:26:00
6405005    2020-01-31 23:17:57
6405006    2020-01-31 22:48:32
6405007    2020-01-31 23:06:00
Name: tpep_dropoff_datetime, Length: 6405008, dtype: str

In [9]:
dtype = {
    "VendorID": "Int64",
    "passenger_count" : "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID" : "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount":"float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge":"float64"
}
parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]


df = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates = parse_dates
)

df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2020-01-01 00:28:15,2020-01-01 00:33:03,1,1.20,1,N,238,239,1,6.00,3.00,0.5,1.47,0.00,0.3,11.27,2.5
1,1,2020-01-01 00:35:39,2020-01-01 00:43:04,1,1.20,1,N,239,238,1,7.00,3.00,0.5,1.50,0.00,0.3,12.30,2.5
2,1,2020-01-01 00:47:41,2020-01-01 00:53:52,1,0.60,1,N,238,238,1,6.00,3.00,0.5,1.00,0.00,0.3,10.80,2.5
3,1,2020-01-01 00:55:23,2020-01-01 01:00:14,1,0.80,1,N,238,151,1,5.50,0.50,0.5,1.36,0.00,0.3,8.16,0.0
4,2,2020-01-01 00:01:58,2020-01-01 00:04:16,1,0.00,1,N,193,193,2,3.50,0.50,0.5,0.00,0.00,0.3,4.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6405003,<NA>,2020-01-31 22:51:00,2020-01-31 23:22:00,<NA>,3.24,<NA>,<NA>,237,234,<NA>,17.59,2.75,0.5,0.00,0.00,0.3,21.14,0.0
6405004,<NA>,2020-01-31 22:10:00,2020-01-31 23:26:00,<NA>,22.13,<NA>,<NA>,259,45,<NA>,46.67,2.75,0.5,0.00,12.24,0.3,62.46,0.0
6405005,<NA>,2020-01-31 22:50:07,2020-01-31 23:17:57,<NA>,10.51,<NA>,<NA>,137,169,<NA>,48.85,2.75,0.0,0.00,0.00,0.3,51.90,0.0
6405006,<NA>,2020-01-31 22:25:53,2020-01-31 22:48:32,<NA>,5.49,<NA>,<NA>,50,42,<NA>,27.17,2.75,0.0,0.00,0.00,0.3,30.22,0.0
6405007,<NA>,2020-01-31 22:44:00,2020-01-31 23:06:00,<NA>,11.60,<NA>,<NA>,179,205,<NA>,54.56,2.75,0.5,0.00,0.00,0.3,58.11,0.0

In [10]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2020-01-01 00:28:15,2020-01-01 00:33:03,1,1.2,1,N,238,239,1,6.0,3.0,0.5,1.47,0.0,0.3,11.27,2.5
1,1,2020-01-01 00:35:39,2020-01-01 00:43:04,1,1.2,1,N,239,238,1,7.0,3.0,0.5,1.50,0.0,0.3,12.30,2.5
2,1,2020-01-01 00:47:41,2020-01-01 00:53:52,1,0.6,1,N,238,238,1,6.0,3.0,0.5,1.00,0.0,0.3,10.80,2.5
3,1,2020-01-01 00:55:23,2020-01-01 01:00:14,1,0.8,1,N,238,151,1,5.5,0.5,0.5,1.36,0.0,0.3,8.16,0.0
4,2,2020-01-01 00:01:58,2020-01-01 00:04:16,1,0.0,1,N,193,193,2,3.5,0.5,0.5,0.00,0.0,0.3,4.80,0.0

In [11]:
df.tpep_dropoff_datetime

0         2020-01-01 00:33:03
1         2020-01-01 00:43:04
2         2020-01-01 00:53:52
3         2020-01-01 01:00:14
4         2020-01-01 00:04:16
                  ...
6405003   2020-01-31 23:22:00
6405004   2020-01-31 23:26:00
6405005   2020-01-31 23:17:57
6405006   2020-01-31 22:48:32
6405007   2020-01-31 23:06:00
Name: tpep_dropoff_datetime, Length: 6405008, dtype: datetime64[us]

In [12]:

from sqlalchemy import create_engine
engine = create_engine('postgresql://admin:root@localhost:5432/ny_taxi')
engine

Engine(postgresql://admin:***@localhost:5432/ny_taxi)

In [13]:
print(pd.io.sql.get_schema(df, name='ny_taxi', con=engine))

CREATE TABLE ny_taxi (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [14]:
df.head(0).to_sql(name='ny_taxi', con = engine, if_exists='replace')

0

In [15]:
len(df)

6405008

In [16]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000
)

df_iter

In [17]:
df=next(df_iter)
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2020-01-01 00:28:15,2020-01-01 00:33:03,1,1.2,1,N,238,239,1,6.0,3.0,0.5,1.47,0.0,0.3,11.27,2.5
1,1,2020-01-01 00:35:39,2020-01-01 00:43:04,1,1.2,1,N,239,238,1,7.0,3.0,0.5,1.50,0.0,0.3,12.30,2.5
2,1,2020-01-01 00:47:41,2020-01-01 00:53:52,1,0.6,1,N,238,238,1,6.0,3.0,0.5,1.00,0.0,0.3,10.80,2.5
3,1,2020-01-01 00:55:23,2020-01-01 01:00:14,1,0.8,1,N,238,151,1,5.5,0.5,0.5,1.36,0.0,0.3,8.16,0.0
4,2,2020-01-01 00:01:58,2020-01-01 00:04:16,1,0.0,1,N,193,193,2,3.5,0.5,0.5,0.00,0.0,0.3,4.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,2020-01-01 14:08:46,2020-01-01 14:19:08,3,1.7,1,N,186,162,2,9.0,2.5,0.5,0.00,0.0,0.3,12.30,2.5
99996,1,2020-01-01 14:21:39,2020-01-01 14:25:46,2,0.9,1,N,229,141,1,5.0,2.5,0.5,1.65,0.0,0.3,9.95,2.5
99997,1,2020-01-01 14:38:26,2020-01-01 14:42:29,1,0.8,1,N,263,75,1,5.0,2.5,0.5,0.83,0.0,0.3,9.13,2.5
99998,1,2020-01-01 14:48:55,2020-01-01 14:58:39,1,1.4,1,N,236,161,1,9.0,2.5,0.5,1.70,0.0,0.3,14.00,2.5
99999,1,2020-01-01 14:19:07,2020-01-01 14:36:15,1,12.5,1,N,132,64,1,34.5,0.0,0.5,7.05,0.0,0.3,42.35,0.0

In [18]:
!uv add tqdm

Resolved 119 packages in 9ms
Checked 10 packages in 11ms

In [19]:
from tqdm.auto import tqdm

In [20]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='ny_taxi', con=engine, if_exists='append')

0it [00:00, ?it/s]